version: 0.2

phases:
  install:
    commands:
      - echo insalling nginx
      - sudo apt-get updat
      - sudo apt-get install nginx -y
  
  build:
    commands:
      - echo buil Started on 'date'
      - cp index.html /var/www/html/index.html

     
artifacts:
  files:
    - /var/www/html/index.html

